### PR TITLE
Solução Training, Biblioteca Data e BaseModel criados | Closed #1 #2 #3

### LINKED ISSUE #1: Criar solução Trainings
Criar uma solução vazia

### LINKED ISSUE #2: Criar uma biblioteca de classes
Criar Data

### LINKED ISSUE #3: Criar BaseModel
Criar pasta model com BaseModel :
int Id

### PR DESCRIPTION
**Pull request by edurw**

### CODE REVIEW

**Review by LeonardoCascaes — CHANGES_REQUESTED** [review]
Bota Public

**Review by bruno41bruno — CHANGES_REQUESTED** [review]
faltou Public no model

**Review by felipesouza16 — APPROVED** [review]

**Review by bruno41bruno — CHANGES_REQUESTED** [review]
Faltou abstract no model

**Review by LeonardoCascaes — APPROVED** [review]

**Review by bruno41bruno — APPROVED** [review]

**Review by felipesouza16 — APPROVED** [review]

**Comment by maykondgranemann** [comment]
Lincar as issues

**Review by maykondgranemann — APPROVED** [review]

**Pull request merged**
